Repository lubusIN/laravel-gymie, pull requests merged in 2025-06, with the labels that each got.

#141 Feat: add Enquiry module
  app/Filament/Resources/EnquiryResource.php
  app/Filament/Resources/EnquiryResource/Pages/CreateEnquiry.php
  app/Filament/Resources/EnquiryResource/Pages/EditEnquiry.php
  app/Filament/Resources/EnquiryResource/Pages/ListEnquiries.php
  app/Filament/Resources/EnquiryResource/Pages/ViewEnquiry.php
  app/Filament/Resources/UserResource.php
  app/Models/Enquiry.php
  composer.json
  composer.lock
  database/factories/EnquiryFactory.php
  database/migrations/2025_05_26_020228_create_enquiries_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/EnquirySeeder.php
Labels: feature

#132 Doc: add README.md file
  README.md
  composer.json
Labels: documentation

#163 Feat(module): Add invoice module
  app/Filament/Pages/Settings.php
  app/Filament/Resources/InvoiceResource.php
  app/Filament/Resources/InvoiceResource/Pages/CreateInvoice.php
  app/Filament/Resources/InvoiceResource/Pages/EditInvoice.php
  app/Filament/Resources/InvoiceResource/Pages/ListInvoices.php
  app/Filament/Resources/InvoiceResource/Pages/ViewInvoice.php
  app/Helpers/helpers.php
  app/Models/Invoice.php
  app/Policies/InvoicePolicy.php
  app/Providers/AppServiceProvider.php
  database/factories/InvoiceFactory.php
  database/migrations/2025_06_13_005807_create_invoices_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/InvoiceSeeder.php
  storage/data/settingsData.json.example
Labels: enhancement

#169 Feat(sidebar-navigation): Organize Admin Sidebar with Navigation Grouping
  app/Filament/Pages/Settings.php
  app/Filament/Resources/EnquiryResource.php
  app/Filament/Resources/FollowUpResource.php
  app/Filament/Resources/InvoiceResource.php
  app/Filament/Resources/MemberResource.php
  app/Filament/Resources/PlanResource.php
  app/Filament/Resources/RoleResource.php
  app/Filament/Resources/ServiceResource.php
  app/Filament/Resources/SubscriptionResource.php
  app/Filament/Resources/UserResource.php
  app/Providers/Filament/AdminPanelProvider.php
  database/migrations/2025_06_15_102321_create_notifications_table.php
Labels: enhancement

#173 Feat(enquiry-form): Added Follow-Up, Lead Owner, and UI Tweaks
  app/Filament/Resources/EnquiryResource.php
  app/Filament/Resources/EnquiryResource/Pages/CreateEnquiry.php
  app/Filament/Resources/EnquiryResource/Pages/EditEnquiry.php
  app/Filament/Resources/EnquiryResource/Pages/ListEnquiries.php
  app/Filament/Resources/EnquiryResource/Pages/ViewEnquiry.php
  app/Models/Enquiry.php
  app/Providers/AppServiceProvider.php
  database/factories/EnquiryFactory.php
  database/migrations/2025_05_26_020228_create_enquiries_table.php
  public/css/app/gymie-styles.css
  resources/css/custom.css
Labels: enhancement

#177 Feat(member-module): Persist & auto-increment member code
  app/Helpers/helpers.php
  app/Models/Member.php
  tests/Unit/InvoiceNumberGeneratorTest.php
  tests/Unit/MemberCodeGeneratorTest.php
Labels: enhancement

#178 Refactor(relationship-name): Standardize Eloquent relationship methods to camelCase
  app/Models/Enquiry.php
  app/Models/Member.php
  app/Models/Plan.php
  app/Models/Service.php
  app/Models/Subscription.php
  app/Providers/AppServiceProvider.php
  config/prevent-deletion.php
Labels: refactor

#188 Feat(plans-table): Add filter by statuses tabs
  app/Filament/Resources/PlanResource.php
  app/Filament/Resources/PlanResource/Pages/CreatePlan.php
  app/Filament/Resources/PlanResource/Pages/EditPlan.php
  app/Filament/Resources/PlanResource/Pages/ListPlans.php
  app/Filament/Resources/PlanResource/Pages/ViewPlan.php
  app/Filament/Resources/SubscriptionResource.php
  app/Models/Plan.php
  app/Models/Subscription.php
Labels: enhancement, refactor
